
<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Flashfm

<!-- badges: start -->
<!-- badges: end -->

The goal of flashfm is to use GWAS summary statistics to jointly fine-map genetic associations for several 
related quantitative traits in a Bayesian framework that leverages information between the traits. 

Website available at: https://jennasimit.github.io/flashfm/.


## System Requirements

Flashfm could be installed with ease on versions of R > 3.6.0 and requires additional steps for R < 3.6.0
If installing on a Windows machine, Rtools must be installed.
Installation time is estimated as 2 minutes.


## Installation Guide

## Short version

``` r
# install.packages("devtools")
devtools::install_github("jennasimit/flashfm")
```

## Longer version (if above fails)

``` r
install.packages("Rcpp")
install.packages("RcppArmadillo")
install.packages("parallel")
install.packages("data.table")
install.packages("gtools")
install.packages("rlist")
install.packages("MASS")
install.packages("xtable")
```

Some packages (e.g. snpStats) are from Bioconductor. For these, you need to do
``` r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("snpStats")
```

R2GUESS, a dependency of GUESSFM, has the dependency mixOmics, which is available from Bioconductor for R versions >=3.5 and at cran in archive form for R < 3.5.

##### R >= 3.5.1:
``` r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("mixOmics")     
```

##### R < 3.5.1:

Go to https://cran.r-project.org/src/contrib/Archive/mixOmics/ and download mixOmics_6.3.2.tar.gz. Then, in R:
``` r
install.packages("mixOmics", repos = "mixOmics_6.3.2.tar.gz", type="source")
```

where if in a different working directory than where the zip file is contained, a file path may be needed for the repos argument.


##### Required dependencies from GitHub

GUESSFM, MFM, and R2BGLiMS are from github and to install do

``` r
install.packages("remotes")
# install and load GUESSFM
remotes::install_github("chr1swallace/GUESSFM","nor2guess")
# install and load MFM
remotes::install_github("jennasimit/MFM")
# install and load R2BGLiMS
remotes::install_github("pjnewcombe/R2BGLiMS")
```

NB: Must have a Java JDK installed in order to install and run R2BGLiMS. This is only needed if you need to run single-trait fine-mapping using JAM. 
If single-trait fine-mapping results are available, then it is not necessary to have Java JDK installed.

``` r
remotes::install_github("jennasimit/flashfm")
library(flashfm)
```

